### ISSUE TITLE
Fix translation to C++

### ISSUE THREAD

**Issue by konard** [linksplatform/Exceptions#47]
https://github.com/linksplatform/Exceptions/blob/75e2aca77197c5fae010de27ee21f1c73d2c4c43/cpp/Platform.Exceptions/IgnoredExceptions.h#L13

In https://github.com/linksplatform/Exceptions/commit/d5166ee43a3f7f11e0a8c55c7ff473dbc949e301 commit translation of this file was broken.
It was run on Linux for the first time. So the hypothesis is that the translator's rules do not support Unix line breaks.

**Comment by konard** [comment]
@uselessgoddess if you would like to do this issue, please assign it to yourself.

**Comment by uselessgoddess** [comment]
Oh. I think, I did it by accident
Could you explain issue details

**Comment by konard** [comment]
Looks like something wrong in how `\r?\n` is handled on Unix by Regex class. https://github.com/linksplatform/RegularExpressions.Transformer.CSharpToCpp/blob/master/csharp/Platform.RegularExpressions.Transformer.CSharpToCpp/CSharpToCppTransformer.cs#L16 
This issue requires investigation.
You can start by adding reproducible bug example [in unit tests](https://github.com/linksplatform/RegularExpressions.Transformer.CSharpToCpp/blob/master/csharp/Platform.RegularExpressions.Transformer.CSharpToCpp.Tests/CSharpToCppTransformerTests.cs).

**Comment by konard** [comment]
Fixed at https://github.com/linksplatform/Exceptions/commit/7bccfc2952f0e0f3a7bea78a115bd7205c08ae9a
