### ISSUE TITLE
Use return of exceptions, instead of implicitly throwing it (throw will be explicit)

### ISSUE THREAD

**Issue by konard** [linksplatform/Exceptions#72]
https://github.com/linksplatform/Exceptions/blob/6549e7798dd8cba362e175dde324662f889235ba/cpp/Platform.Exceptions/ThrowExtensions.h#L3-L9

replace with:

```cpp
auto NotSupportedException() { return std::logic_error("Not supported exception."); }

auto NotImplementedException() { return std::logic_error("Not implemented exception."); }
```

use:

```cpp
throw NotSupportedException();
```

<details open>
<summary>Checklist</summary>

- [X] `cpp/Platform.Exceptions/ThrowExtensions.h` ❌ Failed
<blockquote>• Replace the `throw` keyword with `return` in the `NotSupportedException` function definition. The modified function should look like this: `auto NotSupportedException() { return std::logic_error("Not supported exception."); }`
• Replace the `throw` keyword with `return` in the `NotImplementedException` function definition. The modified function should look like this: `auto NotImplementedException() { return std::logic_error("Not implemented exception."); }`</blockquote>

</details>

**Comment by FreePhoenix888** [comment]
Sweep: do

**Comment by FreePhoenix888** [comment]
Sweep: in cpp/Platform.Exceptions/ThrowExtensions.h we have code like this:
```cpp
 void NotSupportedException() { throw std::logic_error("Not supported exception."); } 
  
 auto NotSupportedExceptionAndReturn() { throw std::logic_error("Not supported exception."); } 
```

Replace `throw` word in such functions to `return`

**Comment by FreePhoenix888** [comment]
Sweep: retry

**Comment by FreePhoenix888** [comment]
Sweep: retry
